// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_run_server`, `get_app`, `list`
// These types are ignored because they are not used by any `pub` functions: `LogMetrics`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `finish`, `tick`

WebHandle runWebServer({required int port, required String path}) =>
    RustLib.instance.api.crateApiWrapperRunWebServer(port: port, path: path);

Future<void> zipDir({required String srcDir, required String dstDir}) =>
    RustLib.instance.api.crateApiWrapperZipDir(srcDir: srcDir, dstDir: dstDir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebHandle>>
abstract class WebHandle implements RustOpaqueInterface {
  String get url;

  set url(String url);

  void cancelServer();
}
